id: ACEBF7FBF
base_file: fE0BD.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:07:00.114002
  last_modified_at: 2022-05-30 22:07:00.114016
