id: ACEBF7FBF
base_file: fF76A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:07:00.119422
  last_modified_at: 2022-05-30 22:07:00.119427
