id: ACEBF7FBF
base_file: f2164.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:07:00.103722
  last_modified_at: 2022-05-30 22:07:00.103734
