id: ACEBF7FBF
base_file: fE278.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:07:00.116291
  last_modified_at: 2022-05-30 22:07:00.116301
