id: ACEBF7FBF
base_file: f7D4F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:07:00.110555
  last_modified_at: 2022-05-30 22:07:00.110561
